React calculator - Milestone 2
bruna-genz/react-calc pull request #4
Opened 2020-06-25 18:04 UTC by bruna-genz

In this milestone, I built the main structure of the app, with the four components:

- App: renders the display and button panel;
- Display: renders the calculation result passed as a prop (currently set to the default "0");
- ButtonPanel: renders all necessary button;
- Button: renders a button with a name, which is passed as a prop from the ButtonPanel component.

2020-06-26 11:27 UTC, shshamim63 requested changes
## Status :recycle: Changes Required :recycle: 
___
Hi @bruna-genz :wave: 
Awesome job :clap: . You almost completed the project. Just need to cover some edge cases and it will be done. Please check the comments below.
___
## :spades: Mandatory Changes :spades: 
___
- You need to specify the type of your props. And you can do it easily by using [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html)
- You have to set the default value for the calcResult. You can do that by following the link provided above.
___
### :clubs: Optional Changes :clubs: 
___
- You can destructure your prop before accessing them.
- Concise readable code is always better than making it long. So check out the comment in your ButtonPanel.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-06-26 11:27 UTC, shshamim63 commented on src/components/Button.js
> +function Button(prop) {
[Optional]
- You can destructure the prop in here. 
```js
function Button({ name }) {
```
Then you can directly use 'name' in your component.

2020-06-26 11:27 UTC, shshamim63 commented on src/components/Display.js
> +function Display(prop) {
[Optional]
- You can apply the same destructure pattern in here for the calcResult.

2020-06-26 11:27 UTC, shshamim63 commented on src/components/Display.js
> +export default Display;
- its calcResult prop should be a String with default value = 0   ([should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png))   ([default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png))

2020-06-26 11:27 UTC, shshamim63 commented on src/components/Button.js
> +export default Button;
its button name prop should be a String ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/validateAsString.png))

2020-06-26 11:27 UTC, shshamim63 commented on src/components/ButtonPanel.js
> +      </div>
[Optional]
- You can refactor these sections by using an array of arrays. Think about it. It will make the code concise.

2020-06-26 15:03 UTC, bruna-genz commented
Thanks, @shshamim63  for the great code review. It was really helpful!

I did all the mandatory and also the optional changes.

2020-06-27 06:20 UTC, fatymahmed approved these changes
## Hi @bruna-genz,
### Great job in this milestone 🎉🎉
### It's a 👍🏾 from me!
## ✔️ Approved!

2020-06-29 14:44 UTC, merged